version: "3.8"
services:
    frontend:
        container_name: project-fe
        restart: always
        build:
            context: .
            dockerfile: ./apps/frontend/Dockerfile
        depends_on:
            - backend
        ports:
            - "5173:5173"
    backend:
        container_name: project-be
        restart: always
        build:
            context: .
            dockerfile: ./apps/backend/Dockerfile
        ports:
            - "6001:6001"
        volumes:
            - automerge-documents:/app/automerge-documents
        environment:
            DATABASE_URL: "postgresql://user:password@project-postgres:5432/database"
            BACKEND_PORT: "6001"
            REDIS_URL: "redis://project-redis:6379"
            NODE_ENV: "dev"
            DATADIR: "automerge-documents"
            WEBSOCKET_PORT: "3030"
        depends_on:
            - postgres
            - redis
        networks:
            - backend-network

    postgres:
        container_name: project-postgres
        restart: always
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "user"
            POSTGRES_DB: "database"
        networks:
            - backend-network

    redis:
        container_name: project-redis
        restart: always
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - backend-network

networks:
    backend-network:

volumes:
    postgres-data:
    automerge-documents:
